name: Single Test

on:
  push:
    branches:
      - master
      - testing

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Convert
        id: convert
        uses: ./
        with:
          text: |
            # Heading 1

            ### :heart: Contributors

            * List Item 1
            * List Item 2

            ### Heading 2 :fun:

            [Link](http://example.com)

            - List Item 3
            - List Item 4

      - name: Verify
        shell: bash
        env:
          ACTUAL: ${{ steps.convert.outputs.text }}
          EXPECTED: |
            *Heading 1*

            *:heart: Contributors*

            •   List Item 1
            •   List Item 2

            *Heading 2 :fun:*

            <http://example.com|Link>

            •   List Item 3
            •   List Item 4
        run: |
          if [ "$ACTUAL" != "$EXPECTED" ]; then
            echo "Actual: '$ACTUAL'"
            echo "Expected: '$EXPECTED'"
            exit 1
          fi
